### ISSUE TITLE
Push fixes upstream

### ISSUE THREAD

**Issue by NicoHood** [arduino/listSerialPortsC#9]
The fork of this software has some changes which are not available upstream:
https://github.com/martinling/libserialport/compare/b5cc9c4f031aee54e8be8f0abb569454213ccad0...master

It would be great to make them available upstream, so one can easier package them.
CC @martinling @facchinm @cmaglie

**Comment by Fitap** [comment]
java.lang.UnsatisfiedLinkError: no listSerialsj in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at processing.app.Platform.<clinit>(Platform.java:157)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at processing.app.BaseNoGui.initPlatform(BaseNoGui.java:527)
        at processing.app.Base.<init>(Base.java:199)
        at processing.app.Base.main(Base.java:144)

eix libserialport
[I] dev-libs/libserialport
     Available versions:  ~0.1.0 0.1.1 **9999 {static-libs udev}
     Installed versions:  0.1.1(19:38:45 01/03/18)(-static-libs)
     Homepage:            http://sigrok.org/wiki/Libserialport
     Description:         Cross platform serial port access library

**Comment by martinling** [comment]
@Fitap, I'm not sure what your comment has to do with this issue, please file a separate bug report for this. However, it looks like you have libserialport installed but are missing the `listSerialsj` JNI library (which uses libserialport, but is not part of the libserialport package). Or you don't have your `java.library.path` set up to include it.

@NicoHood, I hadn't seen this issue before but please note there is a pull request on libserialport to merge changes from Arduino: https://github.com/martinling/libserialport/pull/23 . It's currently awaiting feedback from @facchinm on some comments we had.

**Comment by Fitap** [comment]
Sorry, delete them.
I did wish to add over a comment talking about this issue: java.lang.UnsatisfiedLinkError: no listSerialsj in java.library.path
I don't know how to solve.
Regards.

**Comment by facchinm** [comment]
Hi @martinling .
sorry for that, I've been overwhelmed by other stuff and I totally forgot about it. Will try to get some hours to address the issues you reported.
@Fitap where is that message appearing? In the ArduinoIDE or in another project (which uses the jni wrapper)?

**Comment by Fitap** [comment]
Hi @facchinm the message appears when I run arduinoIDE (in gentoo is arduino) but I run from console, because from menu bar splash screen appears and disappears instantly.

```
fitap@hp-gentoo ~ $ arduino

java.lang.UnsatisfiedLinkError: no listSerialsj in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at processing.app.Platform.<clinit>(Platform.java:157)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at processing.app.BaseNoGui.initPlatform(BaseNoGui.java:527)
        at processing.app.Base.<init>(Base.java:199)
        at processing.app.Base.main(Base.java:144)
``
``
fitap@hp-gentoo ~ $ sudo java-config -l

[xml-commons-external-1.3] Externally-defined set of standard interfaces, namely DOM, SAX, and JAXP (/usr/share/xml-commons-external-1.3/package.env)
[slf4j-api] Simple Logging Facade for Java (/usr/share/slf4j-api/package.env)
[slf4j-simple] Simple Logging Facade for Java (/usr/share/slf4j-simple/package.env)
[jackson-modules-base-2] Annotations for the Java Jackson data processor (/usr/share/jackson-modules-base-2/package.env)
[asm-4] Bytecode manipulation framework for Java (/usr/share/asm-4/package.env)
[bcel] The Byte Code Engineering Library: analyze, create, manipulate Java class files (/usr/share/bcel/package.env)
[jna] Java Native Access (JNA) (/usr/share/jna/package.env)
[ant-core] Java-based build tool similar to 'make' that uses XML configuration files (/usr/share/ant-core/package.env)
[xmlgraphics-commons-2] A library of several reusable components used by Apache Batik and Apache FOP (/usr/share/xmlgraphics-commons-2/package.env)
[jsch] JSch is a pure Java implementation of SSH2 (/usr/share/jsch/package.env)
[xz-java] Implementation of xz data compression in pure java (/usr/share/xz-java/package.env)
[javacup] CUP Parser Generator for Java (/usr/share/javacup/package.env)
[xalan-serializer] DOM Level 3 serializer from Apache Xalan, shared by Xalan and Xerces (/usr/share/xalan-serializer/package.env)
[commons-lang-3.3] Commons components to manipulate core java classes (/usr/share/commons-lang-3.3/package.env)
[rhino-1.6] An open-source implementation of JavaScript written in Java (/usr/share/rhino-1.6/package.env)
[jflex] JFlex is a lexical analyzer generator for Java (/usr/share/jflex/package.env)
[arduino] An open-source AVR electronics prototyping platform (/usr/share/arduino/package.env)
[ant-nodeps] Formerly Ant's optional tasks w/o external deps, now compat empty jar (/usr/share/ant-nodeps/package.env)
[jmdns] JmDNS is an implementation of multi-cast DNS in Java (/usr/share/jmdns/package.env)
[commons-httpclient-3] The Jakarta Commons HttpClient library (/usr/share/commons-httpclient-3/package.env)
[jackson-2] High-performance JSON processor (/usr/share/jackson-2/package.env)
[jzlib] JZlib is a re-implementation of zlib in pure Java (/usr/share/jzlib/package.env)
[commons-compress] Java API for working with archive files (/usr/share/commons-compress/package.env)
[commons-codec] Implementations of common encoders and decoders in Java (/usr/share/commons-codec/package.env)
[jackson-annotations-2] Annotations for the Java Jackson data processor (/usr/share/jackson-annotations-2/package.env)
[commons-net] Java library emulating the client side of many basic Internet protocols (/usr/share/commons-net/package.env)
[jssc] Java Simple Serial Connector (/usr/share/jssc/package.env)
[bcprov-1.58] Java cryptography APIs (/usr/share/bcprov-1.58/package.env)
[commons-logging] An ultra-thin bridge between different Java logging libraries (/usr/share/commons-logging/package.env)
[xalan] Transforming XML documents into HTML, text, or other XML document types (/usr/share/xalan/package.env)
[batik-1.9] Java based SVG toolkit (/usr/share/batik-1.9/package.env)
[commons-io-1] Utility classes, stream implementations, file filters, and endian classes (/usr/share/commons-io-1/package.env)
[jackson-databind-2] Data-binding functionality and tree-model for the Java Jackson data processor (/usr/share/jackson-databind-2/package.env)
[bcpg-1.58] Java cryptography APIs (/usr/share/bcpg-1.58/package.env)

fitap@hp-gentoo ~ $ sudo java-config -L

The following VMs are available for generation-2:
*)      IcedTea JDK 3.6.0 [icedtea-8]
``

``
fitap@hp-gentoo ~ $ locate liblistSerialsj.so

/usr/lib64/liblistSerialsj.so
/usr/lib64/liblistSerialsj.so.1.0.7

fitap@hp-gentoo ~ $ ls -l /usr/lib64/liblistSerialsj.so*
lrwxrwxrwx 1 root root    24 mar  1 19:38 /usr/lib64/liblistSerialsj.so -> liblistSerialsj.so.1.0.7*
-rwxr-xr-x 1 root root 10104 mar  1 19:38 /usr/lib64/liblistSerialsj.so.1.0.7*

```
Regards.

**Comment by facchinm** [comment]
@Fitap I'm not a gentooist but it looks like the IDE is being packaged "incorrectly" since we bundle all the libraries to get rid of any possible pollution at system level. @NicoHood did a great job in packaging the IDE for Arch so maybe he can give a hint on how he solved the `liblistSerialsj` problem.

**Comment by NicoHood** [comment]
I just used the liblistSerial from the Arduino package. I do not recompile it. It was still a plan though but it never worked well. :/

**Comment by Fitap** [comment]
Solve this issue doing following

``export LD_LIBRARY_PATH=/usr/lib64``

Now, arduino runs fine in the terminal box if I setup LD_LIBRARY_PATH.

Regards.
